In [2]:
import numpy as np
import pandas as pd

In [ ]:
#Q1. Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each method and the final output after each method.
data =[[1,2,3,4,5],[6,7,8,9,0]]
array = np.array(data)
array

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
array.ndim

2

In [ ]:
data1 =[[1,2,3,4,5],[6,7,8,9,0],[0,1,3,5,7]]
array1 = np.array(data1)
array1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [0, 1, 3, 5, 7]])

In [ ]:
array1.ndim

2

In [ ]:
array2 = np.zeros((3, 4))
array2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array2.ndim

2

In [ ]:
array3 = np.random.randint(1, 5, size = (3, 4))
array3

array([[1, 4, 4, 4],
       [1, 1, 1, 4],
       [2, 2, 4, 4]])

In [ ]:
array3.ndim

2

In [ ]:
#Q2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1D array into a 2D array.
array1 = np.linspace(1,10,100)

array2 = array1.reshape(10,10)
array2

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909

In [ ]:
#Q4. Generate a 3x3 array with random floating-point numbers between 5 and 20. Then, round each number in the array to 2 decimal places.
array1 = np.random.uniform(5,20,(3,3))
array1

array([[ 5.13227126, 16.09294   , 13.27110418],
       [14.17304983,  6.11790633, 19.38886183],
       [ 7.62253676, 12.41643218, 12.28226325]])

In [ ]:
round_array = np.round(array1, decimals=2)
round_array

array([[ 5.13, 16.09, 13.27],
       [14.17,  6.12, 19.39],
       [ 7.62, 12.42, 12.28]])

In [ ]:
#Q5. Create a NumPy array with random integers between 1 and 10 of shape (5, 6). After creating the array
#a) Extract all even integers from array.
arr = np.random.randint(1, 11,(5,6))
even_array = arr[arr%2==0]
even_array

array([ 4,  4,  2,  8, 10,  2,  2,  8,  6,  6,  4,  2, 10])

In [ ]:
# b) Extract all odd integers from array.
odd_array = arr[arr%2!=0]
odd_array

array([3, 7, 3, 5, 7, 5, 5, 5, 3, 7, 3, 7, 5, 7, 5, 5, 9])

In [ ]:
#Q6.Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the following operations:
#a) Find the indices of the maximum values along each depth level (third axis)
arr = np.random.randint(1,11,(3,3,3))
print(arr)
value = np.argmax(arr, axis= 2)
print("maximum value along each deth level")
value

[[[ 7  9  1]
  [ 3  3  6]
  [ 2  9  7]]

 [[ 3  8  6]
  [ 3  5 10]
  [ 3  6  3]]

 [[ 1  9  8]
  [ 1  9  8]
  [ 6  5  4]]]
maximum value along each deth level


array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 0]])

In [ ]:
# b) Perform element-wise multiplication of between both array.
arr1 = arr*2
print(arr1)
print()
arr2 = value*2
arr2

[[[14 18  2]
  [ 6  6 12]
  [ 4 18 14]]

 [[ 6 16 12]
  [ 6 10 20]
  [ 6 12  6]]

 [[ 2 18 16]
  [ 2 18 16]
  [12 10  8]]]



array([[2, 4, 2],
       [2, 4, 2],
       [2, 2, 0]])

In [4]:
#Q7. Clean and transform the Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.
import pandas as pd
df = pd.read_csv("People Data.csv")
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [ ]:
df['Phone'] = df['Phone'].astype(str).str.replace(r'[^\d]', '', regex=True)

df['Phone'] = pd.to_numeric(df['Phone'])

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Index          1000 non-null   int64  
 1   User Id        1000 non-null   object 
 2   First Name     1000 non-null   object 
 3   Last Name      1000 non-null   object 
 4   Gender         1000 non-null   object 
 5   Email          1000 non-null   object 
 6   Phone          979 non-null    float64
 7   Date of birth  1000 non-null   object 
 8   Job Title      1000 non-null   object 
 9   Salary         1000 non-null   int64  
dtypes: float64(1), int64(2), object(7)
memory usage: 78.2+ KB
None


In [ ]:
#Q8. a) Read the 'data.csv file using pandas, skipping the first 50 rows.
df[0:51]

Index          User Id  First Name Last Name  Gender  \
0       1  8717bbf45cCDbEe      Shelia   Mahoney    Male   
1       2  3d5AD30A4cD38ed          Jo    Rivers  Female   
2       3  810Ce0F276Badec      Sheryl    Lowery  Female   
3       4  BF2a889C00f0cE1     Whitney    Hooper    Male   
4       5  9afFEafAe1CBBB9     Lindsey      Rice  Female   
5       6  aF75e6dDEBC5b66      Sherry  Caldwell    Male   
6       7  efeb05c7Cc94EA3      Ernest   Hoffman    Male   
7       8  fb1BF3FED57E9d7       Doris  Andersen    Male   
8       9  421fAB9a3b98F30      Cheryl      Mays    Male   
9      10  4A42Fe10dB717CB       Harry  Mitchell    Male   
10     11  44FAA9C3CE8DB2B       Casey     Ayala    Male   
11     12  86cCc6417942b4B        Sara      Huff    Male   
12     13  CDA21B6e83Cafe3       Eddie    Barnes  Female   
13     14  1CC30c5F204332e       Ralph      Lowe  Female   
14     15  b4bE3BfBfeBC29e   Priscilla     Davis    Male   
15     16  bFCFDdE5491caE8       Carly    Abbott  Female   
16     17  cEfCEAB1306DbCb     Nicolas  Mckinney    Male   
17     18  aCefF56E59aAf75     Natasha    Macias  Female   
18     19  CF091D6b9Dd4F9c    Courtney   Jenkins  Female   
19     20  462EF46dcaab6EC       Perry   Mcmahon  Female   
20     21  7B247Ca7BbA098d       Emily    Travis    Male   
21     22  dCdadA2bCcFFEAE      Meghan   Hawkins    Male   
22     23  d62fFce33bbccAC      Ernest  Oconnell    Male   
23     24  3Cb9Fe3aB463dba      Norman    Walton  Female   
24     25  be6BBa9EBFeBFcc       Roger   Sweeney  Female   
25     26  a902eE5EABd77DE       Ethan        Wu    Male   
26     27  EEA3bcfe1c7aEAf   Catherine     Myers    Male   
27     28  2Ab20Ed8CfE2D71   Catherine      Nash  Female   
28     29  EC9BCcb3ccEAdE9       Corey   Delgado    Male   
29     30  d6203591c7BEB4F      Hunter      Hahn  Female   
30     31  f67cb59Eea96a23      Dakota     Gomez    Male   
31     32  94c6aF7DEe2Ad7A   Nathaniel    Clarke  Female   
32     33  b1DC89E2d73F0b4       Marco     Reyes    Male   
33     34  FECAedB175FD9f4        Todd     Weber    Male   
34     35  CB41aabFbB8AdDa       Bryan    Vaughn    Male   
35     36  BcdffBD402E5A23    Adrienne   Lambert    Male   
36     37  b00f07E8F6Ecf6e        Seth      Hess    Male   
37     38  8b8Aab259B2a00D    Stefanie   Sherman    Male   
38     39  D060A3eacFBFAEE        Kent     Velez    Male   
39     40  DFAB00C01CcF860      Angela      Huff    Male   
40     41  aDB35cb99a88358       Harry     Moore  Female   
41     42  0269CdeD7B3C8B0  Kristopher    Barnes    Male   
42     43  ddd2B9CcEBEe00E     Rachael   Herrera    Male   
43     44  355e6511Fa0ff55     Vincent    Berger  Female   
44     45  F2f91586dA8f7f5         Don    Bolton    Male   
45     46  99A502C175C4EBd      Olivia      Duke  Female   
46     47  eEF6Cf6C10b1446        Erik   Rosales  Female   
47     48  3eD5c0dDBD0a7DC      Judith      Wall  Female   
48     49  EbD7AF6EDF4831e       Chloe   Ramirez  Female   
49     50  afF3018e9cdd1dA      George    Mercer  Female   
50     51  CccE5DAb6E288e5          Jo    Zavala    Male   

                            Email         Phone Date of birth  \
0             pwarner@example.org  8.571398e+12    27-01-2014   
1   fergusonkatherine@example.net           NaN    26-07-1931   
2             fhoward@example.org  5.997821e+12    25-11-2013   
3           zjohnston@example.com           NaN    17-11-2012   
4                elin@example.net  3.904172e+16    15-04-1923   
5           kaitlin13@example.net  8.537801e+12    06-08-1917   
6          jeffharvey@example.com  9.365575e+15    22-12-1984   
7            alicia33@example.org  4.709523e+12    02-12-2016   
8              jake50@example.com  1.382048e+11    16-12-2012   
9       lanechristina@example.net  5.609035e+16    29-06-1953   
10             ncantu@example.com  8.629884e+12    17-04-2020   
11           kristy41@example.net  1.041859e+16    21-05-1964   
12           brandy23@example.com  8.0

In [ ]:
#Q8. b) Only read the columns: Last Name', 'Gender', "Email", "Phone" and "Salary from the file.
df1 = df[["Last Name","Gender","Email","Phone","Salary"]]
df1

Last Name  Gender                          Email         Phone  Salary
0     Mahoney    Male            pwarner@example.org  8.571398e+12   90000
1      Rivers  Female  fergusonkatherine@example.net           NaN   80000
2      Lowery  Female            fhoward@example.org  5.997821e+12   50000
3      Hooper    Male          zjohnston@example.com           NaN   65000
4        Rice  Female               elin@example.net  3.904172e+16  100000
..        ...     ...                            ...           ...     ...
995    Bryant  Female         lyonsdaisy@example.net  2.177529e+11   90000
996     Barry  Female        dariusbryan@example.com  1.149711e+16   50000
997  Mckinney  Female         georgechan@example.org  1.750774e+18   60000
998    Phelps    Male            wanda04@example.net  9.152922e+12  100000
999      Tran  Female        deannablack@example.org  7.975254e+16   90000

[1000 rows x 5 columns]

In [ ]:
#Q8. c) Display the first 10 rows of the filtered dataset.
df1[0:10]

Last Name  Gender                          Email         Phone  Salary
0   Mahoney    Male            pwarner@example.org  8.571398e+12   90000
1    Rivers  Female  fergusonkatherine@example.net           NaN   80000
2    Lowery  Female            fhoward@example.org  5.997821e+12   50000
3    Hooper    Male          zjohnston@example.com           NaN   65000
4      Rice  Female               elin@example.net  3.904172e+16  100000
5  Caldwell    Male          kaitlin13@example.net  8.537801e+12   50000
6   Hoffman    Male         jeffharvey@example.com  9.365575e+15   60000
7  Andersen    Male           alicia33@example.org  4.709523e+12   65000
8      Mays    Male             jake50@example.com  1.382048e+11   50000
9  Mitchell    Male      lanechristina@example.net  5.609035e+16   50000

In [5]:
#Q8. d) Extract the Salary column as a Series and display its last 5 values.
s1 = pd.Series(list(df['Salary'][0:5]))
s1

0     90000
1     80000
2     50000
3     65000
4    100000
dtype: int64

In [7]:
#Q9. Filter and select rows from the People Dataset, where the "Last Name' column contains the name "Duke', Gender column contains the word Female and 'Salary' should be less than 85000.
data = pd.read_csv("People Data.csv")

filtered_data = data[(data["Last Name"] == "Duke") & (data["Gender"] == "Female") & (data["Salary"] < 85000)]

print(filtered_data)

     Index          User Id First Name Last Name  Gender  \
45      46  99A502C175C4EBd     Olivia      Duke  Female   
210    211  DF17975CC0a0373    Katrina      Duke  Female   
457    458  dcE1B7DE83c1076      Traci      Duke  Female   
729    730  c9b482D7aa3e682     Lonnie      Duke  Female   

                        Email                   Phone Date of birth  \
45        diana26@example.net  001-366-475-8607x04350    13-10-1934   
210       robin78@example.com            740.434.0212    21-09-1935   
457  perryhoffman@example.org     +1-903-596-0995x489    11-02-1997   
729   kevinkramer@example.net            982.692.6257    12-05-2015   

           Job Title  Salary  
45           Dentist   60000  
210  Producer, radio   50000  
457        Herbalist   50000  
729     Nurse, adult   70000  


In [10]:
#Q10. Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6?
data = np.random.randint(1,7, size=35)

df = pd.DataF(data.reshape(7,5))

df

AttributeError: module 'pandas' has no attribute 'DataFream'